using static System.Console;
using System;
using System.IO;
using System.Collections;

// using Kiogas;

/*
Kyogas	C#

str string
int int
flt float
uint uint
byte byte
bool bool
arr <type>[]
*/

class Stringify
{
    // a collection of each snippet generated by HandleStringification
    private static readonly List<string> KyogasSnippets = [];
    
    // receives a key and a value from the dictionary
    // then translates the C# type into the respective Kyogas type
    private static string HandleStringification<TKey, TValue>(TKey key, TValue value)
    {
        var result = key switch
        {
            string stringVar => $"str {stringVar}: {value}",
            int integer      => $"int {integer}: {value}",
            float floatVar   => $"flt {floatVar}: {value}",
            uint uInteger    => $"uint {uInteger}: {value}",
            byte byteVar     => $"byte {byteVar}: {value}",
            _ => ""
        };
        return result;
    }

    private static void StoreString(string stringToStore)
    {
        KyogasSnippets.Add(stringToStore);
    }

    private static void WriteSnippets()
    {
        try 
        {
            File.WriteAllLines("data.kyo", KyogasSnippets);
        } 
        catch 
        {
            WriteLine("An error occured while writing to data.kyo");
        }
        
    }
    
    public static void Process<TKey, TValue>(IDictionary<TKey, TValue> csharpObject)
    {
        if (csharpObject.Count == 0)
        {
            throw new Exception("You passed an empty dictionary to Stringify; you cannot stringify an empty dictionary.");
        }
        
        // end guard clauses


        // the actual logic
        foreach (var pair in csharpObject)
        {
            if (pair.Key is null)
            {
                throw new Exception($"You passed a null key to Stringify in: {pair}; {pair.Key} is null");
            }
            
            if (pair.Value is null)
            {
                throw new Exception($"You passed a null value to Stringify in: {pair}; {pair.Value} is null");
            }
            
            var parsedString = HandleStringification(pair.Key, pair.Value);

            if ((string.IsNullOrEmpty(parsedString) == false))
            {
                StoreString(parsedString);
            }
        }
    }
}

/*
Test payload:

var test_dict = new Dictionary<string, bool> {
    {"death is in love with us", true},
    {"trashed, lost, and strung out", true}
};

Stringify.Main(test_dict);

*/
